region     = "put-your-region-here"
access_key = "put-your-access-key-here"
secret_key = "put-your-secret-key-here"
project =    "put-your-project-tag"
name     =   "put-your-name-tag"
vpc_cidr =   "X.X.X.X/X"
sbit     =   "X"